sudo: required
language: node_js
node_js:
    - 10.16.0
before_install:
  - export PJ_repo=$PJ_scope/$PJ_name
  - export PJ_src=projects/$PJ_repo
  - export PJ_dist=dist/$PJ_repo
  - export demo_build=dist/BRAND
  - BUILD=`date +%s`; sed -ie "s/BUILD/$BUILD/g" ./src/environments/environment.prod.ts
install:
  - npm i
script:
  - npm run lint
  #- npx ng build @$PJ_scope/$PJ_name
  - npx ng test --watch=false --code-coverage
  - npx ng build --prod --deploy-url /$PJ_name/ --base-href /$PJ_name/
cache:
    directories:
      - node_modules
after_success:
  - npm install codecov -g
  - codecov
  - ls dist/BRAND
  - ls $demo_build
  - echo 'DONE'
before_deploy:
  - if [[ $TRAVIS_TAG ]]; then
      if [[ $PWD != *$PJ_dist ]]; then
        cd $PJ_dist;
      fi;
    fi;
deploy:
  - provider: pages
    local_dir: $demo_build
    github_token: $github
    skip_cleanup: true
    keep_history: true
    deployment_file: true

